### ISSUE TITLE
Add Degree of Contribution

### ISSUE THREAD

**Issue by JulianFrattini** [andreas-bauer/credit-maker#7]
An optional extension to the CRediT taxonomy is the use of contributor roles, which replace a binary assignment of contributors to roles with a more fine-grained distinction. The official implementation guidelines[^1] describe them as follows:

>**Degree of contribution optional** – where multiple individuals serve in the same role, the degree of contribution can optionally be specified as ‘lead’, ‘equal’, or ‘supporting’

While still considered optional, being able to toggle the assignment mode from `binary` to `degree of contribution` would be a fantastic addition that improves the applicability of this tool.

[^1]: https://credit.niso.org/implementing-credit/

**Comment by michaeldorner** [comment]
You are ahead of your time, @JulianFrattini :-)
I understand where you come from. However:

> ‘Degree of contribution’ […] is not currently part of the CRediT standard

Let’s keep it with the standard, I would say. @andreas-bauer ?

**Comment by andreas-bauer** [comment]
@JulianFrattini I've looked into this before, but I couldn't find a satisfactory solution. I'm open to integrating a solution, but only if it doesn't decrease the easy-to-use user experience.
Let me know if you have an idea of how to implement it.

I see the following options:

## Replace Checkboxes with Dropdown Lists
Only a small list indicator (similar in size to the checkbox) would fit. How should each state be represented in a meaningful way that reduces ambiguity? Additionally, I assume that using dropdowns for many contributors could be cumbersome.

## Multi-State Checkboxes
Changing the checkboxes to support multiple states is a solution that doesn't require additional space and is fairly easy to use. However, we need to decide how to represent the different states—color, symbols, etc.—in a way that is clearly explained in the UI. Otherwise, it could cause more confusion than it helps.

Check out [react-three-state-checkbox](https://www.npmjs.com/package/react-three-state-checkbox).

## Separate Template
Having separate templates that add all possible degree options after each contribution type is currently available as the template "Plain text with degree options". It requires some cleanup work after being copied into the targeted document.

**Comment by michaeldorner** [comment]
… and it’s not in the standard. ;-)
